MCQ/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MCQ.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^quiz/', include('quiz.urls', namespace="quiz")),
    url(r'', include('homepage.urls', namespace="homepage")),
)

# if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL,
#                          document_root=settings.STATIC_ROOT)
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.conf.urls import patterns, url

from quiz import views

urlpatterns = patterns('',
                       url(r'^$', views.get_user_detail,
                           name='get_user_detail'),
                       url(r'^quiz/$', views.quiz, name='quiz'),
                       url(r'^result/$', views.result, name='result'),
                       url(r'^charts/simple/$', views.draw_graph,
                           name='draw_graph'),
                       )

quiz/models.py
from django.db import models

TITLE_CHOICES = (
    ('MR', 'Male'),
    ('MRS', 'Female'),
    ('MS', 'Other'),
)


class Question(models.Model):
    question_text = models.CharField(max_length=100)
    answer_text = models.CharField(max_length=100)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=100)

    def __str__(self):
        return self.choice_text


class UserDetail(models.Model):
    sex = models.CharField(max_length=10, choices=TITLE_CHOICES)
    name = models.CharField(max_length=100)
    email_id = models.EmailField(max_length=70, unique=True)
    birth_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name


class ResultPercentage(models.Model):
    # 0% - 25%
    firstquarter = models.IntegerField(default=0)
    # 25% - 50%
    secondquarter = models.IntegerField(default=0)
    # 50% - 75%
    thirdquarter = models.IntegerField(default=0)
    # 75% - 100%
    fourthquarter = models.IntegerField(default=0)
    fifthquarter = models.IntegerField(default=0)

    def updatepercentage(self, percent):
        if percent > 0 and percent <= 25.0:
            self.firstquarter += 1
        elif percent <= 50 and percent > 25:
            self.secondquarter += 1
        elif percent > 50 and percent <= 75:
            self.thirdquarter += 1
        elif percent > 75 and percent <= 100:
            self.fourthquarter += 1

quiz/forms.py
from django.forms import ModelForm
from django import forms
from quiz.models import UserDetail


# Create the form
class UserDetailForm(ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    class Meta:
        model = UserDetail
        fields = ["name", "sex", "email_id", "birth_date"]

    def __init__(self, *args, **kwargs):
        super(UserDetailForm, self).__init__(*args,  **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control',
                                                 'placeholder': 'Name'})
        self.fields['sex'].widget.attrs.update({'class': 'form-control',
                                                'placeholder': ''})
        self.fields['email_id'].widget.attrs.update({'class': 'form-control',
                                                     'placeholder':
                                                     'someone@gmail.com'})
        self.fields['birth_date'].widget.attrs.update({'class': 'form-control',
                                                       'placeholder':
                                                       'YYYY-MM-DD'})


class QuestionForm(forms.Form):
    title = forms.ChoiceField(widget=forms.RadioSelect())

    def __init__(self, question="", *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = question.question_text
        self.fields['title'].choices = \
            [([question.id, chi.choice_text], chi)
             for chi in question.choice_set.all()]

quiz/views.py
from __future__ import division
from django.shortcuts import render, redirect
from quiz.models import Question, ResultPercentage
from quiz.forms import UserDetailForm, QuestionForm
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure

questions = []
DEBUG = True


def get_user_detail(request):
    if request.method == "POST":
        form = UserDetailForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            # Save the name in session in the name so it can be used in
            # results.html
            request.session["name"] = request.POST["name"]
            return redirect("/quiz/quiz/")
        else:
            print form.errors
    else:
        form = UserDetailForm()

    return render(request, 'quiz/register.html', {'form': form})


def quiz(request):
    global questions
    questions = Question.objects.all()
    FORM = []
    if request.method == "POST":
        choice = request.POST.get("title")
        if choice:
            k, v = eval(choice)
            request.session[str(k)] = v
        if DEBUG:
            print "request.session==================>", request.session.items()
            print "request.session[name]==================>",\
                request.session.get("name")
        page = request.session.get("page")
        if page <= request.session.get("num_pages"):
            url_ = "/quiz/quiz/?page={0}".format(page)
        else:
            # return HttpResponse("Reached the Final Page")
            url_ = "/quiz/result/"
        return redirect(url_)
    else:
        for q in questions:
            form = QuestionForm(q)
            FORM.append(form)
        paginator = Paginator(FORM, 1)
        print "request.GET==================>", request.GET
        page = request.GET.get("page")
        print "request.pageno==================>", paginator.num_pages
        request.session["num_pages"] = int(paginator.num_pages)
        try:
            if page:
                pages = int(page) + 1
                request.session["page"] = pages
            FORM = paginator.page(page)
        except PageNotAnInteger:
            FORM = paginator.page(1)
            request.session["page"] = 2
        except EmptyPage:
            FORM = paginator.page(
                paginator.num_pages)
        return render(request, 'quiz/questions.html', {'FORM': FORM})


def result(request):
    choice = {}
    print request.session.items()
    for i in questions:
        key = str(i.id)
        choice[i] = request.session.get(key, False)
    quest_answered = len([v for v in choice.values() if v])
    correct_answer_count = 0
    for k, v in choice.items():
        if v:
            if k.answer_text.strip() == str(v).strip():
                correct_answer_count += 1
    percentage_ = (correct_answer_count / 14)*100
    # Convert the floating point with two decimal points
    percentage = float("{0:.2f}".format(percentage_))
    tmp = ResultPercentage.objects.all()[0]
    # Custom model method which checks for the range of percentages
    # and saves the values accordingly
    tmp.updatepercentage(percentage)
    # Save the database
    tmp.save()
    result_dict = {'No of questions answered': quest_answered,
                   'No of answers you got right': correct_answer_count,
                   'Percentage': percentage}
    context = {'question_list': questions,
               'choice_': choice,
               'result_dict': result_dict,
               'name': request.session.get("name"),
               }
    # Clear the current sessions
    request.session.flush()
    return render(request, 'quiz/results.html', context)


def draw_graph(request):
    tmp = ResultPercentage.objects.all()[0]
    # Fetch data from the database and pass it to pie
    data = [tmp.firstquarter, tmp.secondquarter, tmp.thirdquarter,
            tmp.fourthquarter]
    explode = (0.05, 0.05, 0.05, 0.05)

    fig = Figure(facecolor='white', figsize=(6, 6), frameon=False, dpi=300)
    ax = fig.add_subplot(111, aspect='equal')
    ax.pie(data,
           explode=explode,
           shadow=False,
           labels=['0% -25%', '25%-50%', '50%-75%', '75%-100%'],
           colors=['b', 'r', 'g'],
           )
    canvas = FigureCanvas(fig)
    response = HttpResponse(content_type="image/png")
    canvas.print_figure(response, dpi=300)
    return response

quiz/templates/quiz/index.html
{% extends 'base.html' %}
{%block content %}
{% if question_list %}
<form action={% url "quiz:next" %} method="post">
        {% csrf_token %}
        <ul style="list-style-type:none">
         {% for question in question_list %}
            <li><h3 align="left">Q{{question.id }} . {{ question.question_text }}</h3></li> 
		<table class="table table-hover">
			<tbody>
            {% for choice in question.choice_set.all %}
			<tr>
				<td align="left">
					<input type="radio" name="{{question.id}}" id="choice{{ forloop.counter}}" value=" {{ choice.choice_text}} " class = "form-radio"/>
			<label for="choice{{ forloop.counter }}"> 
				{{ choice.choice_text }}
			</label>
		</td>
	</tr>
            {% endfor %}
	</tbody>
	</table>
         {% endfor %}
        </ul>
        <input type="submit" value="Submit" class="btn btn-small btn-primary btn-block" role="button"/>
	</form>
{% endif %}
{% endblock %}

quiz/templates/quiz/questions.html
{% extends "base.html" %}
{% block content %}
<head>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js">
	</script>
	<script>
	$(document).ready(function() {
	    $('.panel .table tr').click(function(event) {
		        if (event.target.type !== 'radio') {
					            $(':radio', this).trigger('click');
								        }
										    });
											});
	</script>

</head>
<form action={% url 'quiz:quiz' %} method="post">
{% csrf_token %}
{% for form in FORM %}
{% for field in form %}
<h1 align=left> 
    {{ field.label }} 
</h1>
{% endfor %}
</br>
<div class="panel panel-default">
  <table class="table table-hover" >
    {% for field in form.title %}
      <tr>
        <td align=left>
           {{ field }}
        </td>
      </tr>
    {% endfor %}	
  </table>
</div>
</br>
</br>
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if FORM.has_previous %}
            <!--a href="?page={{ FORM.previous_page_number }}">previous</a-->
            <a class="btn btn-large btn-primary"  href="?page={{ FORM.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ FORM.number }} of {{ FORM.paginator.num_pages }}
        </span>

        {% if FORM.has_next %}
			<input type="submit" value="Next" class="btn btn-large btn-primary " role="button"/>
            <!--a href="?page={{ FORM.next_page_number }}">next</a-->
		{% else %}
			<input type="submit" value="Submit" class="btn btn-large btn-primary " role="button"/>
        {% endif %}
    </span>
</div>
</form>
{%endblock %}

quiz/templates/quiz/register.html
{% extends 'base.html' %}
{% block content %}

<h1> Registration Form </h1>

</br>
</br>

<form id="userdetailform" action="{% url 'quiz:get_user_detail' %}" method="post" class="form-horizontal" role="form">
  {% csrf_token %}
  <div class="col-xs-12">
    {% for field in form %}
      <div class="form-group">
        {{field.label_tag }}
        {{ field }}
		{{ field.errors }}
      </div>
    {%endfor %}
  </div>
<button type="submit" class="btn btn-primary btn-lg active"> Submit </button>
</form>

{% endblock %}

quiz/templates/quiz/results.html
{% extends 'base.html' %}
{% block content %}
{% if question_list %}
<div class="container-fluid">
  <div class="row">
   <!-- Detailed report -->
    <div class="col-sm-3 col-md-2 col-md-offset-1 sidebar">
    <!--div class="col-md-4" -->
      <div class="panel panel-primary nav nav-sidebar">
          <div class="panel-heading">
            <h1 class="panel-title"><i class="fa fa-info-circle fa-lg"></i> Detailed Report </h1>
          </div>
          <div class="panel-body">
              {% for k,v in choice_.items %}
                  <table class="table table-striped table-bordered">
                      <thead style="background-color: black">
                          <tr>
                              <th>
                                  <font color="white">Q{{forloop.counter}} . {{ k.question_text }} </font>
                              </th>
                          </tr>
                      </thead>
                      <tbody>
                          <tr>
                              <td>
                                  <strong> Selected Answer - {{ v }} </strong>
                              </td>
                          </tr>
                          <tr>
                              <td>
                                  <strong> Correct Answer  - {{k.answer_text}} </strong>
                              </td>
                          </tr>
                      </tbody>
                  </table>
              {% endfor %}
          </div><!--/.panel-body-->
      </div><!--/.panel .panel-primary .nav .nav-sidebar-->
    </div><!--/.sidebar-->

    <!-- Percentage Part -->
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main ">
    <!--div class="col-md-8 col-md-offset-5 main" -->
      <div class="panel panel-primary">
          <div class="panel-heading">
            <h1 class="panel-title text-uppercase"> <i class="fa fa-rocket fa-2x"></i> {{ name }}, Your Score is!!! </h1>
          </div>
          <div class="panel-body">
              <table class="table table-hover table-bordered">
                  <tbody>
                      {% for k,v in result_dict.items %}
                          <tr class="info">
                              <td>
                                  <h6> <strong> {{ forloop.counter }} </strong></h6>
                              </td>
                              <td >
                                  <h4>
                                      <p class="text-uppercase">
                                          <strong> {{ k }} </strong>
                                      </p>
                                  </h4>
                              </td>
                              <td>
                                  <h5><strong> {{ v }} </strong></h5>
                              </td>
                          </tr>
                      {% endfor %}
                  </tbody>
              </table> 
        </div><!--/.panel-body-->
      </div><!--/.panel .panel-primary-->
    <!--/div-->
    <!-- Graph Part -->
    <!--div class="col-md-8"-->
      <div class="panel panel-primary">
          <div class="panel-heading">
            <h1 class="panel-title text-uppercase"> <i class="fa fa-pie-chart fa-2x"></i>  where do you stand</h1>
          </div>
          <div class="panel-body" >
             <img src="{% url 'quiz:draw_graph' %}"  class="img-responsive img-circle center-block" alt="Results Pie Chart" width="400" height="400">
          </div>
      </div><!--/.panel-primary-->
    </div><!--/.main-->
  </div><!--/.row-->
</div><!--/.container-fluid-->

{% endif %}
{% endblock %}