MCQ/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MCQ.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^quiz/', include('quiz.urls', namespace="quiz")),
    url(r'', include('homepage.urls', namespace="homepage")),
)

# if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL,
#                          document_root=settings.STATIC_ROOT)
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.conf.urls import patterns, url

from homepage import views


urlpatterns = patterns('',
                       url(r'^$', views.index,
                           name='index'),
                       )

quiz/urls.py
from django.conf.urls import patterns, url

from quiz import views

urlpatterns = patterns('',
                       url(r'^$', views.get_user_detail,
                           name='get_user_detail'),
                       url(r'^quiz/$', views.quiz, name='quiz'),
                       url(r'^result/$', views.result, name='result'),
                       url(r'^charts/simple/$', views.draw_graph,
                           name='draw_graph'),
                       )

quiz/models.py
from django.db import models

TITLE_CHOICES = (
    ('MR', 'Male'),
    ('MRS', 'Female'),
    ('MS', 'Other'),
)


class Question(models.Model):
    question_text = models.CharField(max_length=100)
    answer_text = models.CharField(max_length=100)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=100)

    def __str__(self):
        return self.choice_text


class UserDetail(models.Model):
    sex = models.CharField(max_length=10, choices=TITLE_CHOICES)
    name = models.CharField(max_length=100)
    email_id = models.EmailField(max_length=70, unique=True)
    birth_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name


class ResultPercentage(models.Model):
    # 0% - 25%
    firstquarter = models.IntegerField(default=0)
    # 25% - 50%
    secondquarter = models.IntegerField(default=0)
    # 50% - 75%
    thirdquarter = models.IntegerField(default=0)
    # 75% - 100%
    fourthquarter = models.IntegerField(default=0)
    fifthquarter = models.IntegerField(default=0)

    def updatepercentage(self, percent):
        if percent > 0 and percent <= 25.0:
            self.firstquarter += 1
        elif percent <= 50 and percent > 25:
            self.secondquarter += 1
        elif percent > 50 and percent <= 75:
            self.thirdquarter += 1
        elif percent > 75 and percent <= 100:
            self.fourthquarter += 1

quiz/forms.py
from django.forms import ModelForm
from django import forms
from quiz.models import UserDetail


# Create the form
class UserDetailForm(ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    class Meta:
        model = UserDetail
        fields = ["name", "sex", "email_id", "birth_date"]

    def __init__(self, *args, **kwargs):
        super(UserDetailForm, self).__init__(*args,  **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control',
                                                 'placeholder': 'Name'})
        self.fields['sex'].widget.attrs.update({'class': 'form-control',
                                                'placeholder': ''})
        self.fields['email_id'].widget.attrs.update({'class': 'form-control',
                                                     'placeholder':
                                                     'someone@gmail.com'})
        self.fields['birth_date'].widget.attrs.update({'class': 'form-control',
                                                       'placeholder':
                                                       'YYYY-MM-DD'})


class QuestionForm(forms.Form):
    title = forms.ChoiceField(widget=forms.RadioSelect())

    def __init__(self, question="", *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = question.question_text
        self.fields['title'].choices = \
            [([question.id, chi.choice_text], chi)
             for chi in question.choice_set.all()]

quiz/views.py
from __future__ import division
from django.shortcuts import render, redirect
from quiz.models import Question, ResultPercentage
from quiz.forms import UserDetailForm, QuestionForm
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure

questions = []
DEBUG = True


def get_user_detail(request):
    if request.method == "POST":
        form = UserDetailForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            # Save the name in session in the name so it can be used in
            # results.html
            request.session["name"] = request.POST["name"]
            return redirect("/quiz/quiz/")
        else:
            print form.errors
    else:
        form = UserDetailForm()

    return render(request, 'quiz/register.html', {'form': form})


def quiz(request):
    global questions
    questions = Question.objects.all()
    FORM = []
    if request.method == "POST":
        choice = request.POST.get("title")
        if choice:
            k, v = eval(choice)
            request.session[str(k)] = v
        if DEBUG:
            print "request.session==================>", request.session.items()
            print "request.session[name]==================>",\
                request.session.get("name")
        page = request.session.get("page")
        if page <= request.session.get("num_pages"):
            url_ = "/quiz/quiz/?page={0}".format(page)
        else:
            # return HttpResponse("Reached the Final Page")
            url_ = "/quiz/result/"
        return redirect(url_)
    else:
        for q in questions:
            form = QuestionForm(q)
            FORM.append(form)
        paginator = Paginator(FORM, 1)
        print "request.GET==================>", request.GET
        page = request.GET.get("page")
        print "request.pageno==================>", paginator.num_pages
        request.session["num_pages"] = int(paginator.num_pages)
        try:
            if page:
                pages = int(page) + 1
                request.session["page"] = pages
            FORM = paginator.page(page)
        except PageNotAnInteger:
            FORM = paginator.page(1)
            request.session["page"] = 2
        except EmptyPage:
            FORM = paginator.page(
                paginator.num_pages)
        return render(request, 'quiz/questions.html', {'FORM': FORM})


def result(request):
    choice = {}
    print request.session.items()
    for i in questions:
        key = str(i.id)
        choice[i] = request.session.get(key, False)
    quest_answered = len([v for v in choice.values() if v])
    correct_answer_count = 0
    for k, v in choice.items():
        if v:
            if k.answer_text.strip() == str(v).strip():
                correct_answer_count += 1
    percentage_ = (correct_answer_count / 14)*100
    # Convert the floating point with two decimal points
    percentage = float("{0:.2f}".format(percentage_))
    tmp = ResultPercentage.objects.all()[0]
    # Custom model method which checks for the range of percentages
    # and saves the values accordingly
    tmp.updatepercentage(percentage)
    # Save the database
    tmp.save()
    result_dict = {'No of questions answered': quest_answered,
                   'No of answers you got right': correct_answer_count,
                   'Percentage': percentage}
    context = {'question_list': questions,
               'choice_': choice,
               'result_dict': result_dict,
               'name': request.session.get("name"),
               }
    # Clear the current sessions
    request.session.flush()
    return render(request, 'quiz/results.html', context)


def draw_graph(request):
    tmp = ResultPercentage.objects.all()[0]
    # Fetch data from the database and pass it to pie
    data = [tmp.firstquarter, tmp.secondquarter, tmp.thirdquarter,
            tmp.fourthquarter]
    explode = (0.05, 0.05, 0.05, 0.05)

    fig = Figure(facecolor='white', figsize=(6, 6), frameon=False, dpi=300)
    ax = fig.add_subplot(111, aspect='equal')
    ax.pie(data,
           explode=explode,
           shadow=False,
           labels=['0% -25%', '25%-50%', '50%-75%', '75%-100%'],
           colors=['b', 'r', 'g'],
           )
    canvas = FigureCanvas(fig)
    response = HttpResponse(content_type="image/png")
    canvas.print_figure(response, dpi=300)
    return response

quiz/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title> Cdelta - Quiz </title>

    <!-- Bootstrap core CSS -->
    <!--link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet"-->
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/yeti/bootstrap.min.css" rel="stylesheet">

    <!-- Fontawesome -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!--link href="/static/css/starter-template.css" rel="stylesheet"-->
    <link href={% static "quiz/css/starter-template.css" %}  rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src={% static "quiz/js/ie-emulation-modes-warning.js" %}></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	  <a class="navbar-brand" href="{% url 'homepage:index' %}"><i class="fa fa-home fa-fw"></i>&nbsp;CDelta</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#about">About</a></li>
            <li><a href="#about">Rules</a></li>
            <li><a href="#about">Feedback</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid-->
    </nav>

     <div class="container">

      <div class="starter-template">
	      {% block content %}
	      
	      {% endblock%}
      </div>

    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src={% static "quiz/js/ie10-viewport-bug-workaround.js" %}></script>
  </body>
</html>